// =============================================================================
// sprite-gen.js
//
// Icon-sprite generation, shared by scripts/build-site.mjs (workbench sprite,
// every icon) and the packers (viewer sprite, the small subset the artifact
// UI uses). The viewer sprite is written to src/viewer/sprite.js so the
// bundled artifact carries its icons inline — the artifact stays fully
// self-contained (invariant #1), no <use> ever resolves over the network.
//
// Node-only (fs/path): imported by the pack path and the build script, never
// by browser code — browser code imports the GENERATED sprite modules.
// =============================================================================

import fs from 'fs';
import path from 'path';

/** Icons the artifact UI ships (a subset of site/icons). */
export const VIEWER_ICONS = ['pin', 'close', 'eye', 'eye-off', 'export'];

/**
 * Build one inline SVG sprite from vendored Lucide files.
 * Each file is `<svg ...>…geometry…</svg>`; only the geometry is kept and
 * wrapped in a <symbol>. Stroke styling comes from CSS (.ico) at use sites.
 * @param {string} iconsDir directory containing <name>.svg files
 * @param {string[]} names icon names to include (no extension)
 * @returns {string} the sprite markup
 */
export function buildSprite(iconsDir, names) {
  const symbols = names.map((name) => {
    const svg = fs.readFileSync(path.join(iconsDir, name + '.svg'), 'utf8')
      .split('<!--').map((part, i) => (i === 0 ? part : part.slice(part.indexOf('-->') + 3))).join('');
    const inner = (svg.match(/<svg[^>]*>([\s\S]*?)<\/svg>/) || [, ''])[1].trim();
    return `<symbol id="i-${name}" viewBox="0 0 24 24">${inner}</symbol>`;
  }).join('');
  return `<svg class="icon-sprite" xmlns="http://www.w3.org/2000/svg" aria-hidden="true">${symbols}</svg>`;
}

/**
 * Generate src/viewer/sprite.js (gitignored) from the vendored icons, so the
 * viewer bundle can inject its own sprite at boot.
 * @param {string} rootDir repository root
 */
export function ensureViewerSprite(rootDir) {
  const sprite = buildSprite(path.join(rootDir, 'site', 'icons'), VIEWER_ICONS);
  fs.writeFileSync(path.join(rootDir, 'src', 'viewer', 'sprite.js'),
    `// AUTO-GENERATED by src/pack/sprite-gen.js — do not edit.\nexport const SPRITE = ${JSON.stringify(sprite)};\n`);
}
