#!/usr/bin/env node
// Builds the site. Everything the workbench needs at runtime is bundled or
// generated here so the site works even over file:// (no fetch at runtime):
//
//   - src/app/sprite.js   generated inline SVG sprite (from site/icons/*.svg),
//                         bundled into app.js and injected on load.
//   - site/export-assets.js  window.__EXPORT = { viewer, tpl, css }, loaded by
//                         a <script> tag so export needs no fetch.
//   - site/app.js         the minified workbench bundle.
//
// Generated files (sprite.js, export-assets.js, app.js, assets/) are gitignored.
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import * as esbuild from 'esbuild';

const __dir = path.dirname(fileURLToPath(import.meta.url));
const R = (...p) => path.join(__dir, '..', ...p);

fs.mkdirSync(R('site', 'assets'), { recursive: true });

// --- 1. generate the inline icon sprite from site/icons/*.svg ---------------
// Each Lucide file is `<svg ...>…geometry…</svg>`; we keep only the geometry
// and wrap it in a <symbol>. Stroke styling is applied in CSS (.ico), so the
// symbols carry no colour — they inherit currentColor at use sites.
const iconsDir = R('site', 'icons');
const symbols = fs.readdirSync(iconsDir)
  .filter((f) => f.endsWith('.svg'))
  .map((f) => {
    const name = f.replace('.svg', '');
    const svg = fs.readFileSync(path.join(iconsDir, f), 'utf8').replace(/<!--[\s\S]*?-->/g, '');
    const inner = (svg.match(/<svg[^>]*>([\s\S]*?)<\/svg>/) || [, ''])[1].trim();
    return `<symbol id="i-${name}" viewBox="0 0 24 24">${inner}</symbol>`;
  })
  .join('');
const sprite = `<svg class="icon-sprite" xmlns="http://www.w3.org/2000/svg" aria-hidden="true">${symbols}</svg>`;
fs.writeFileSync(R('src', 'app', 'sprite.js'),
  `// AUTO-GENERATED by scripts/build-site.mjs — do not edit.\nexport const SPRITE = ${JSON.stringify(sprite)};\n`);

// --- 2. build the artifact viewers ------------------------------------------
for (const entry of ['boot-geo.js', 'boot-gltf.js']) {
  esbuild.buildSync({
    entryPoints: [R('src', 'viewer', entry)],
    bundle: true, minify: true, format: 'iife',
    outfile: R('site', 'assets', 'viewer-' + entry.replace('boot-', '').replace('.js', '') + '.js'),
  });
}

// --- 3. inline the export assets (no fetch at export time) ------------------
const exportAssets = {
  viewer: fs.readFileSync(R('site', 'assets', 'viewer-gltf.js'), 'utf8'),
  tpl: fs.readFileSync(R('src', 'template', 'page.html'), 'utf8'),
  css: fs.readFileSync(R('src', 'template', 'page.css'), 'utf8'),
};
fs.writeFileSync(R('site', 'export-assets.js'),
  `window.__EXPORT=${JSON.stringify(exportAssets)};`);

// --- 4. build the workbench bundle (imports the generated sprite) ----------
// node:fs / node:path stay external: @gltf-transform/core lazily imports them
// on its NodeIO path only, which the site never constructs (it uses WebIO).
esbuild.buildSync({
  entryPoints: [R('src', 'app', 'main.js')],
  bundle: true, minify: true, format: 'iife', outfile: R('site', 'app.js'),
  external: ['node:fs', 'node:path'],
});

console.log('site built in site/ :',
  fs.readdirSync(R('site')).filter((f) => !f.startsWith('.')).join(', '));
